version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    image: python:latest
    #restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "True"
      APP_PORT: 5001
      MONGODB_DATABASE: motim_points
      MONGODB_USERNAME: kodesmil
      MONGODB_PASSWORD: kodesmil
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/var/www
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: motim_points
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: alpine:latest
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
