apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kodesmil-ingress
  namespace: local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: activities.local.api.kodesmil.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kodesmil-activities
              servicePort: 5000
    - host: survey.local.api.kodesmil.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kodesmil-survey
              servicePort: 5000
    - host: locations.local.api.kodesmil.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kodesmil-locations
              servicePort: 5000
    - host: products.local.api.kodesmil.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kodesmil-products
              servicePort: 5000
    - host: points.local.api.kodesmil.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kodesmil-points
              servicePort: 5000
    - host: notifications.local.api.kodesmil.com
      http:
        paths:
          - path: /
            backend:
              serviceName: go-notifications
              servicePort: 50051
