apiVersion: v1
kind: Service
metadata:
  labels:
    run: kodesmil-locations
  name: kodesmil-locations
spec:
  ports:
  - name: app
    port: 5000
    targetPort: 5000
  type: NodePort
  selector:
    run: kodesmil-locations