version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kodesmil_products_flask
    image: python:latest
    #restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_DATABASE: kodesmil_products
      MONGODB_USERNAME: # DB USERNAME
      MONGODB_PASSWORD: # PASSWORD
      MONGODB_HOSTNAME: # DB HOSTNAME
      AUTH0_DOMAIN: # AUTH0 URL
      API_IDENTIFIER: # AUTH0 API IDENTIFIER
    volumes:
      - .:/var/www

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: alpine:latest
    container_name: kodesmil_products_webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - kodesmil_products_flask

volumes:
  appdata:
    driver: local
  nginxdata:
    driver: local
