version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kodesmil_activities_flask
    image: kodesmil/kodesmil_activities_flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_DATABASE: kodesmil_activities
      MONGODB_USERNAME: # DB USERNAME
      MONGODB_PASSWORD: # PASSWORD
      MONGODB_HOSTNAME: # DB HOSTNAME
    volumes:
      - .:/var/www

volumes:
  appdata:
    driver: local