apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: kodesmil_universe
build:
  artifacts:
    - image: kodesmil/kodesmil_activities
      context: flask_activities
    - image: kodesmil/kodesmil_locations
      context: flask_locations
    - image: kodesmil/kodesmil_points
      context: flask_points
    - image: kodesmil/kodesmil_products
      context: flask_products
    - image: kodesmil/kodesmil_survey
      context: flask_survey
deploy:
  kubectl:
    manifests:
      - deployment/namespace_prod/namespace.yaml
      - deployment/namespace_prod/env.yaml
      - deployment/namespace_prod/secret.yaml
      - deployment/namespace_prod/ingress.yaml
      - deployment/kodesmil_activities/deployment.yaml
      - deployment/kodesmil_activities/service.yaml
      - deployment/kodesmil_locations/deployment.yaml
      - deployment/kodesmil_locations/service.yaml
      - deployment/kodesmil_points/deployment.yaml
      - deployment/kodesmil_points/service.yaml
      - deployment/kodesmil_products/deployment.yaml
      - deployment/kodesmil_products/service.yaml
      - deployment/kodesmil_survey/deployment.yaml
      - deployment/kodesmil_survey/service.yaml
