apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kodesmil-survey
  name: kodesmil-survey
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kodesmil-survey
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: kodesmil-survey
    spec:
      containers:
        - name: kodesmil-survey
          ports:
            - containerPort: 5000
          env:
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: kodesmil-env
                  key: flask.app.debug
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: kodesmil-env
                  key: flask.app.flavor
            - name: APP_PORT
              value: "5000"
            - name: MONGODB_DB_SURVEY
              value: kodesmil_survey
            - name: MONGODB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: mongodb.hostname
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: mongodb.password
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: mongodb.username
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secrets/firebase-service-config.json"
          image: kodesmil/kodesmil_survey
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          volumeMounts:
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: kodesmil-secret-files
