apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: go-notifications
  name: go-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-notifications
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: go-notifications
    spec:
      containers:
        - name: go-notifications
          ports:
            - containerPort: 50051
          env:
            - name: APP_PORT
              value: "50051"
            - name: MONGODB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: mongodb.hostname
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: mongodb.password
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: mongodb.username
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secrets/firebase-service-config.json"
          image: kodesmil/go_notifications
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          volumeMounts:
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: kodesmil-secret-files
