apiVersion: v1
kind: Service
metadata:
  labels:
    run: go-notifications
  name: go-notifications
spec:
  ports:
  - name: app
    port: 50051
    targetPort: 50051
  type: NodePort
  selector:
    run: go-notifications