apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kodesmil-locations
  name: kodesmil-locations
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kodesmil-locations
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: kodesmil-locations
    spec:
      containers:
        - name: kodesmil-locations
          ports:
            - containerPort: 5000
          env:
            - name: APP_DEBUG
              value: "True"
            - name: APP_ENV
              value: prod
            - name: APP_PORT
              value: "5000"
            - name: MONGODB_DB_LOCATIONS
              value: kodesmil_locations
            - name: MONGODB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: MONGODB_HOSTNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: MONGODB_PASSWORD
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: MONGODB_USERNAME
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: AUTH0_DOMAIN
            - name: API_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: kodesmil-secret
                  key: API_IDENTIFIER
          image: kodesmil/kodesmil_locations:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"