apiVersion: v1
kind: Service
metadata:
  labels:
    run: kodesmil-activities
  name: kodesmil-activities
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    run: kodesmil-activities
  type: NodePort
