apiVersion: v1
kind: Service
metadata:
  labels:
    run: kodesmil-activities
  name: kodesmil-activities-load-balancer
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30157
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: kodesmil-activities
  sessionAffinity: None
  type: LoadBalancer
